logging:
  #  pattern:
  #    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  #    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org:
      springframework: INFO

spring:
  application:
    name: element-test-app

server:
  port: 8080

element:
  insurance:
    name: "Insurance configuration"
    modules:

      bike:
        coverage:
          min: 0
          max: 3000
        risk: 0.3

      jewelry:
        coverage:
          min: 500
          max: 10000
        risk: 0.05

      electronics:
        coverage:
          min: 500
          max: 6000
        risk: 0.35

      sports-equipment:
        coverage:
          min: 0
          max: 20000
        risk: 0.3
